units:
  - id: 0635da23-b766-4b31-867a-f5cd8d8a75d0
    name: mililitre
    symbol: ml
    system: METRIC
    type: VOLUME

  - id: b7be3558-95e0-45bc-9642-c726ed89ee65
    name: litre
    symbol: l
    system: METRIC
    type: VOLUME
  
  - id: 96800d6f-1028-4c67-b96c-78a92c6e2f62
    name: pinch
    system: IMPERIAL
    type: VOLUME
  
  - id: dbc7acdb-ca86-4279-bae4-f45ed0787806
    name: dash
    system: IMPERIAL
    type: VOLUME

  - id: dd1cffb9-28d9-48a0-a18b-eb8c3461f5d6
    name: teaspoon
    symbol: tsp
    system: IMPERIAL
    type: VOLUME
  
  - id: 62b2a398-d186-4561-a2e3-c39ad4f90ff0
    name: tablespoon
    symbol: tbsp
    system: IMPERIAL
    type: VOLUME
  
  - id: d4a8e6c0-aa1a-4888-8983-baea160287fd
    name: fluid ounce
    symbol: fl oz
    system: IMPERIAL
    type: VOLUME
  
  - id: 3fcba6e1-6c1d-4c4a-9d68-d8db83e69ab9
    name: cup
    symbol: c
    system: IMPERIAL
    type: VOLUME
  
  - id: 396dacfe-ffa8-4ba4-a3c9-3358b167290c
    name: gram
    symbol: g
    system: METRIC
    type: MASS
  
  - id: 4ba57bd0-fe1f-4f7d-930f-32b287eff3fd
    name: kilogram
    symbol: kg
    system: METRIC
    type: MASS
  
  - id: 64c31568-b9a3-4427-99df-6b6afb482e49
    name: ounce
    symbol: oz
    system: IMPERIAL
    type: MASS
  
  - id: 09bb3e6e-ea90-4f06-84cd-3e905919620d
    name: pound
    symbol: lb
    system: IMPERIAL
    type: MASS
  
  - id: 2c0dc7c3-e5a5-40fc-aa22-23e63f570465
    name: count
    
  - id: 9028b48e-69cf-4ced-9bbc-c1ebbf4768eb
    name: to taste
